/* eslint-disable quote-props */
export default [
  {
    'id': '1',
    'companyName': 'Sweatpants USA',
    'companyUrl': 'sweatpantsusa.com',
    'companyEmail': 'customerservice@company.com',
    'contestName': 'April 2020 Sweatpant Giveaway',
    'isActive': 'true',
    'imageUrl': 'https://contest-landing-page--maximus222.repl.co/SWEATPANTS%20USA.jpg',
    'contestDescription': 'Sed ut perspiciatis unde omnis iste natus error sit voluptate accusantium doloremque laudantium, totam rem aperiam.Eaque ipsa quae ab illo inventore veritatis et quasi architect beatae vitae dicta sunt explicabo.',
    'contestValue': '$400.00',
    'officialRulesUrl': '/',
    'contactEmail': 'person@company.com',
    'businessMailingAddress': '1839 N Main St.',
    'businessState': 'Utah',
    'businessZip': '83204',
    'startDate': '4/1/2020',
    'startTime': '12:00:00 AM, MT',
    'endDate': '4/30/2020',
    'endTime': '11:59:59 PM, MT',
    'timezone': 'Eastern Time (EDT)',
    'impressions': '5002',
    'participants': '910',
    'referredParticipants': '320',
    'conversionRate': '18%',
    'participantsList': [
      {
        'participantId': '1',
        'isConfirmed': 'false',
        'firstName': 'Bob',
        'lastName': 'Smith',
        'numberOfEntries': '11',
        'email': 'bsmith@company.com',
        'referredBy': 'Sally Smith',
        'numberOfReferrals': '1',
      },
      {
        'participantId': '33',
        'isConfirmed': 'false',
        'firstName': 'Something',
        'lastName': 'Smith',
        'numberOfEntries': '21',
        'email': 'ssmith@company.com',
        'referredBy': 'Sally Smith',
        'numberOfReferrals': '2',
      },
    ],
  },
  {
    'id': '2',
    'companyName': 'Sweatpants USA',
    'companyUrl': '/',
    'companyEmail': 'customerservice@company.com',
    'contestName': 'April 2020 T-Shirt Giveaway',
    'isActive': 'true',
    'imageUrl': '',
    'contestDescription': 'Sed ut perspiciatis unde omnis iste natus error sit voluptate accusantium doloremque laudantium, totam rem aperiam.Eaque ipsa quae ab illo inventore veritatis et quasi architect beatae vitae dicta sunt explicabo.',
    'contestValue': '$400.00',
    'startDate': '4/1/2020',
    'startTime': '12:00:00 AM, MT',
    'officialRulesUrl': '/',
    'endDate': '4/30/2020',
    'endTime': '11:59:59 PM, MT',
    'timezone': 'Eastern Time (EDT)',
    'impressions': '3724',
    'participants': '378',
    'referredParticipants': '189',
    'conversionRate': '10%',
    'participantsList': [
      {
        'participantId': '34',
        'isConfirmed': 'false',
        'firstName': 'Bob',
        'lastName': 'Smith',
        'numberOfEntries': '11',
        'email': 'bsmith@company.com',
        'referredBy': 'Sally Smith',
        'numberOfReferrals': '1',
      },
      {
        'participantId': '35',
        'isConfirmed': 'false',
        'firstName': 'Something',
        'lastName': 'Smith',
        'numberOfEntries': '21',
        'email': 'ssmith@company.com',
        'referredBy': 'Sally Smith',
        'numberOfReferrals': '2',
      },
    ],
  },
  {
    'id': '3',
    'companyName': 'Sweatpants USA',
    'companyUrl': '/',
    'companyEmail': 'customerservice@company.com',
    'contestName': 'March 2020 Giveaway',
    'isActive': 'false',
    'imageUrl': '',
    'contestDescription': 'Sed ut perspiciatis unde omnis iste natus error sit voluptate accusantium doloremque laudantium, totam rem aperiam.Eaque ipsa quae ab illo inventore veritatis et quasi architect beatae vitae dicta sunt explicabo.',
    'contestValue': '$400.00',
    'startDate': '4/1/2020',
    'startTime': '12:00:00 AM, MT',
    'officialRulesUrl': '/',
    'endDate': '4/30/2020',
    'endTime': '11:59:59 PM, MT',
    'timezone': 'Eastern Time (EDT)',
    'impressions': '0',
    'participants': '0',
    'referredParticipants': '0',
    'conversionRate': '0%',
    'numberOfParticipants': [],
  },
  {
    'id': '4',
    'companyName': 'Sweatpants USA',
    'companyUrl': '/',
    'companyEmail': 'customerservice@company.com',
    'contestName': 'February 2020 Giveaway',
    'isActive': 'false',
    'imageUrl': '',
    'contestDescription': 'Sed ut perspiciatis unde omnis iste natus error sit voluptate accusantium doloremque laudantium, totam rem aperiam.Eaque ipsa quae ab illo inventore veritatis et quasi architect beatae vitae dicta sunt explicabo.',
    'contestValue': '$400.00',
    'startDate': '4/1/2020',
    'startTime': '12:00:00 AM, MT',
    'endDate': '4/30/2020',
    'endTime': '11:59:59 PM, MT',
    'timezone': 'Eastern Time (EDT)',
    'officialRulesUrl': '/',
    'impressions': '0',
    'participants': '0',
    'referredParticipants': '0',
    'conversionRate': '0%',
    'numberOfParticipants': [],
  },
  {
    'id': '5',
    'companyName': 'Sweatpants USA',
    'companyUrl': '/',
    'companyEmail': 'customerservice@company.com',
    'contestName': 'January 2020 Giveaway',
    'isActive': 'false',
    'imageUrl': '',
    'contestDescription': 'Sed ut perspiciatis unde omnis iste natus error sit voluptate accusantium doloremque laudantium, totam rem aperiam.Eaque ipsa quae ab illo inventore veritatis et quasi architect beatae vitae dicta sunt explicabo.',
    'contestValue': '$400.00',
    'startDate': '4/1/2020',
    'startTime': '12:00:00 AM, MT',
    'endDate': '4/30/2020',
    'endTime': '11:59:59 PM, MT',
    'timezone': 'Eastern Time (EDT)',
    'officialRulesUrl': '/',
    'impressions': '0',
    'participants': '0',
    'referredParticipants': '0',
    'conversionRate': '0%',
    'numberOfParticipants': [],
  },
];
